services:
  web:
    build:
      context: .
      target: dev
      args:
        UID: ${UID:-10001}
        GID: ${GID:-10001}

    ports:
      - 8000:8000

    stdin_open: true
    tty: true
    volumes:
      - .:/app

  mariadb:
    image: mariadb:10-jammy
    environment:
      MYSQL_ROOT_PASSWORD: "moderator"
      MYSQL_USER: "moderator"
      MYSQL_PASSWORD: "moderator"
      MYSQL_DATABASE: "moderator"

    volumes:
      - moderatorvolume:/var/lib/mysql

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  moderatorvolume: {}
