---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator
  namespace: moderator-stage
  labels:
    app: moderator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator
  template:
    metadata:
      labels:
        app: moderator
    spec:
      containers:
      - name: moderator-web
        image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/moderator:8775f29a70f15b55a9f87cc0f62521b30b93f301
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: moderator-stage
        - secretRef:
            name: moderator-stage
