# Generated by Django 5.2.13 on 2026-04-29 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderate", "0020_event_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional: Helpful links, additional information",
                validators=[django.core.validators.MaxLengthValidator(2500)],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(
                validators=[
                    django.core.validators.MaxLengthValidator(500),
                    django.core.validators.MinLengthValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                default="",
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
    ]
